# docker-compose.yml
services:
  web:
    build: .
    env_file:
      - .env
    depends_on:
      - bot
    restart: unless-stopped
    expose:
      - "5000"

  bot:
    build: .
    env_file:
      - .env
    command: python modules/botTelegram.py
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - certbot-data:/etc/letsencrypt
      - nginx-log:/var/log/nginx
    depends_on:
      - web
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-data:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    command: >
      certonly --webroot
      --webroot-path=/var/www/certbot
      --email kuning.denis@gmail.com
      --agree-tos
      --no-eff-email
      -d cbdc.kongius.ru
      -d www.cbdc.kongius.ru
    depends_on:
      - nginx

volumes:
  certbot-data:
  nginx-log: